"""
Django settings for carfriend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Load the project's .env into os.environ for EVERY code path (gunicorn,
# manage.py, shell, signals) so SUREPASS_TOKEN / FAST2SMS_API_KEY etc. resolve
# regardless of which module is imported first. override=False keeps any real
# environment variables authoritative. The .env lives one level above the Django
# project root (e.g. /var/www/carfriend/.env); also try the project root.
load_dotenv(BASE_DIR.parent / ".env")
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-ll@5=mw0mx%0rx92ed$4^3_u6)rr9ea+h@uo)+r^%h@d0^lhln")
DEBUG      = config("DEBUG", default=True, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=".localhost,.carfriend.in,localhost,127.0.0.1").split(",")
# When True, the public www surface serves a maintenance page (staff hosts stay
# up). Default False so deploying this never takes the live site down — flip it
# in the prod .env when you actually want the maintenance page.
MAINTENANCE_MODE = config("MAINTENANCE_MODE", default=False, cast=bool)

AUTH_USER_MODEL = "accounts.User"


# Application definition

INSTALLED_APPS = [
    "django_hosts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # third-party
    "rest_framework",
    "channels",
    # carfriend apps
    "core",
    "accounts",
    "kyc",
    "vehicles",
    "inspections",
    "auctions",
    "crm",
    "deals",
    "payments",
    "notifications",
    "www",
]

SITE_ID = 1

MIDDLEWARE = [
    "django_hosts.middleware.HostsRequestMiddleware",
    # Runs after host resolution so request.host is known; gates only the public
    # www surface when MAINTENANCE_MODE is on.
    "core.middleware.MaintenanceMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_hosts.middleware.HostsResponseMiddleware",
]

ROOT_URLCONF = "carfriend.urls_public"
ROOT_HOSTCONF = "carfriend.hosts"
DEFAULT_HOST = "www"
PARENT_HOST = os.environ.get("PARENT_HOST", "localhost")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "template", BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ── Authentication ──────────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# ── django-allauth ──────────────────────────────────────────────────────────
ACCOUNT_LOGIN_METHODS         = {"email"}
ACCOUNT_EMAIL_REQUIRED        = True
ACCOUNT_USERNAME_REQUIRED     = False
ACCOUNT_EMAIL_VERIFICATION    = "none"
ACCOUNT_SIGNUP_REDIRECT_URL   = "/auth/role-redirect/"
LOGIN_REDIRECT_URL            = "/auth/role-redirect/"
LOGOUT_REDIRECT_URL           = "/"
ACCOUNT_LOGOUT_ON_GET         = True

SOCIALACCOUNT_AUTO_SIGNUP     = True
SOCIALACCOUNT_LOGIN_ON_GET    = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

WSGI_APPLICATION = "carfriend.wsgi.application"
ASGI_APPLICATION = "carfriend.asgi.application"
CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
# Live test-drive GPS broadcast (ws/drive/<report_id>/). OFF by default; store-and-
# replay always works. Set True to let Admin/customer watch a drive live.
DRIVE_LIVE_BROADCAST = False


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'carfriend_db',
        'USER': 'minaketan',
        'PASSWORD': 'Mina@2001',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Inspection videos can be up to 400 MB raw (compressed server-side after).
# Accept them, and spool anything over 5 MB to a temp file on disk so a 400 MB
# upload never loads into RAM. NOTE: Nginx `client_max_body_size` must be raised
# to match (e.g. `client_max_body_size 450M;`) and gunicorn `--timeout` bumped
# (e.g. 600) or large uploads 413 / the worker is killed mid-transcode.
DATA_UPLOAD_MAX_MEMORY_SIZE = 419430400           # 400 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880             # 5 MB → spool to disk past this

CARFRIEND_LOGO_PATH = BASE_DIR / "static" / "images" / "carfriend-plate-logo.png"

# Third-party integration keys (never hard-code real values)
DIGIO = {
    "BASE_URL": os.environ.get("DIGIO_BASE_URL", ""),
    "CLIENT_ID": os.environ.get("DIGIO_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("DIGIO_CLIENT_SECRET", ""),
}
FCM_SERVER_KEY = os.environ.get("FCM_SERVER_KEY", "")
WHATSAPP = {"TOKEN": os.environ.get("WA_TOKEN", ""), "PHONE_ID": os.environ.get("WA_PHONE_ID", "")}
SMS = {"API_KEY": os.environ.get("SMS_API_KEY", ""), "SENDER": os.environ.get("SMS_SENDER", "CARFRD")}

NOTIFY_SYNC_FALLBACK = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
