"""
Django settings for carfriend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ll@5=mw0mx%0rx92ed$4^3_u6)rr9ea+h@uo)+r^%h@d0^lhln"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [".localhost", ".carfriend.in", "localhost", "127.0.0.1"]

AUTH_USER_MODEL = "accounts.User"


# Application definition

INSTALLED_APPS = [
    "django_hosts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "channels",
    "core",
    "accounts",
    "kyc",
    "vehicles",
    "inspections",
    "auctions",
    "crm",
    "deals",
    "payments",
    "notifications",
    "www",
]

MIDDLEWARE = [
    "django_hosts.middleware.HostsRequestMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_hosts.middleware.HostsResponseMiddleware",
]

ROOT_URLCONF = "carfriend.urls_public"
ROOT_HOSTCONF = "carfriend.hosts"
DEFAULT_HOST = "www"
PARENT_HOST = os.environ.get("PARENT_HOST", "localhost")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "template", BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "carfriend.wsgi.application"
ASGI_APPLICATION = "carfriend.asgi.application"
CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'carfriend_db',
        'USER': 'minaketan',
        'PASSWORD': 'Mina@2001',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CARFRIEND_LOGO_PATH = BASE_DIR / "static" / "images" / "carfriend-plate-logo.png"

# Third-party integration keys (never hard-code real values)
DIGIO = {
    "BASE_URL": os.environ.get("DIGIO_BASE_URL", ""),
    "CLIENT_ID": os.environ.get("DIGIO_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("DIGIO_CLIENT_SECRET", ""),
}
FCM_SERVER_KEY = os.environ.get("FCM_SERVER_KEY", "")
WHATSAPP = {"TOKEN": os.environ.get("WA_TOKEN", ""), "PHONE_ID": os.environ.get("WA_PHONE_ID", "")}
SMS = {"API_KEY": os.environ.get("SMS_API_KEY", ""), "SENDER": os.environ.get("SMS_SENDER", "CARFRD")}

NOTIFY_SYNC_FALLBACK = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
