# Generated by Django 5.2.12 on 2026-06-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=60)),
                ("model", models.CharField(max_length=80)),
                ("variant", models.CharField(blank=True, max_length=80)),
                ("year", models.PositiveIntegerField()),
                ("reg_number", models.CharField(blank=True, max_length=20)),
                ("ownership", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("expected_price", models.PositiveIntegerField(default=0)),
                (
                    "condition_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A (Excellent)"),
                            ("B", "B (Good)"),
                            ("C", "C (Fair)"),
                            ("D", "D (Poor)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("est_market_value", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("inspecting", "Inspection in progress"),
                            ("approved", "Inspection approved"),
                            ("listed", "Listed / auction"),
                            ("sold", "Sold"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("fuel", models.CharField(blank=True, max_length=20)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicles/thumbnails/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rc", "RC"),
                            ("insurance", "Insurance"),
                            ("service", "Service history"),
                        ],
                        max_length=12,
                    ),
                ),
                ("file", models.FileField(upload_to="vehicles/docs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicles/photos/")),
                ("section", models.CharField(blank=True, max_length=40)),
                ("plate_masked", models.BooleanField(default=False)),
                ("gps_lat", models.FloatField(blank=True, null=True)),
                ("gps_lng", models.FloatField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
