# Generated by Django 5.2.15 on 2026-06-05 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkpoints", models.JSONField(blank=True, default=dict)),
                ("score", models.PositiveIntegerField(default=0)),
                ("condition_grade", models.CharField(blank=True, max_length=1)),
                ("est_market_value", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="inspections/reports/"
                    ),
                ),
                ("is_synced", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        max_length=6,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=40)),
                ("file", models.FileField(upload_to="inspections/media/raw/")),
                (
                    "masked_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="inspections/media/masked/"
                    ),
                ),
                ("plate_masked", models.BooleanField(default=False)),
                ("gps_lat", models.FloatField(blank=True, null=True)),
                ("gps_lng", models.FloatField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="inspections.inspectionreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DentMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("label", models.CharField(blank=True, max_length=80)),
                ("severity", models.PositiveSmallIntegerField(default=1)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dents",
                        to="inspections.inspectionreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("inprogress", "In Progress"),
                            ("submitted", "Submitted (awaiting Admin)"),
                            ("approved", "Admin Approved"),
                            ("rejected", "Rejected"),
                            ("reinspect", "Re-inspection requested"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="visit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="inspections.inspectionvisit",
            ),
        ),
    ]
