# Generated by Django 5.2.12 on 2026-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionmedia",
            name="mp4_file",
            field=models.FileField(
                blank=True, null=True, upload_to="inspections/media/mp4/"
            ),
        ),
        migrations.AddField(
            model_name="inspectionmedia",
            name="slot",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="inspectionmedia",
            name="webp_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="inspections/media/webp/"
            ),
        ),
        migrations.AlterField(
            model_name="inspectionmedia",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="inspections/media/raw/"
            ),
        ),
        migrations.AlterField(
            model_name="inspectionmedia",
            name="kind",
            field=models.CharField(
                choices=[("photo", "Photo"), ("video", "Video"), ("audio", "Audio")],
                default="photo",
                max_length=6,
            ),
        ),
    ]
