"""Preset checkpoint definitions for each inspection section."""

CHECKPOINT_MAP = {
    "basic": [
        {"key": "ownership_doc", "label": "Ownership document available"},
        {"key": "rc_book",       "label": "RC Book present"},
        {"key": "insurance",     "label": "Insurance valid"},
        {"key": "pollution",     "label": "Pollution certificate"},
        {"key": "service_hist",  "label": "Service history available"},
        {"key": "odometer",      "label": "Odometer reading"},
        {"key": "fuel_type",     "label": "Fuel type matches"},
        {"key": "color_match",   "label": "Color matches RC"},
    ],
    "exterior": [
        {"key": "front_bumper",  "label": "Front bumper"},
        {"key": "rear_bumper",   "label": "Rear bumper"},
        {"key": "hood",          "label": "Hood / bonnet"},
        {"key": "roof",          "label": "Roof"},
        {"key": "front_windshield", "label": "Front windshield"},
        {"key": "rear_windshield",  "label": "Rear windshield"},
        {"key": "left_fender",   "label": "Left fender"},
        {"key": "right_fender",  "label": "Right fender"},
        {"key": "left_door_f",   "label": "Left door (front)"},
        {"key": "left_door_r",   "label": "Left door (rear)"},
        {"key": "right_door_f",  "label": "Right door (front)"},
        {"key": "right_door_r",  "label": "Right door (rear)"},
        {"key": "boot",          "label": "Boot / trunk"},
        {"key": "paint_condition","label": "Paint condition"},
        {"key": "rust",          "label": "Rust / corrosion"},
        {"key": "panel_gaps",    "label": "Panel alignment/gaps"},
        {"key": "headlights",    "label": "Headlights"},
        {"key": "taillights",    "label": "Tail lights"},
    ],
    "interior": [
        {"key": "dashboard",     "label": "Dashboard condition"},
        {"key": "steering",      "label": "Steering wheel"},
        {"key": "seats_front",   "label": "Front seats"},
        {"key": "seats_rear",    "label": "Rear seats"},
        {"key": "seat_belts",    "label": "Seat belts"},
        {"key": "carpet",        "label": "Carpet / floor mat"},
        {"key": "ac",            "label": "Air conditioning"},
        {"key": "heater",        "label": "Heater"},
        {"key": "infotainment",  "label": "Infotainment / stereo"},
        {"key": "windows_elec",  "label": "Power windows"},
        {"key": "central_lock",  "label": "Central locking"},
        {"key": "sunroof",       "label": "Sunroof (if applicable)"},
        {"key": "odor",          "label": "Interior odor"},
        {"key": "roof_lining",   "label": "Roof lining"},
    ],
    "engine": [
        {"key": "engine_start",  "label": "Engine starts normally"},
        {"key": "engine_noise",  "label": "Engine noise"},
        {"key": "oil_leak",      "label": "Oil leaks"},
        {"key": "coolant_leak",  "label": "Coolant leaks"},
        {"key": "oil_level",     "label": "Oil level"},
        {"key": "coolant_level", "label": "Coolant level"},
        {"key": "battery",       "label": "Battery condition"},
        {"key": "belt_condition","label": "Belt condition"},
        {"key": "exhaust_smoke", "label": "Exhaust smoke"},
        {"key": "turbo",         "label": "Turbocharger (if applicable)"},
        {"key": "ac_compressor", "label": "AC compressor"},
        {"key": "engine_mounts", "label": "Engine mounts"},
    ],
    "tyres": [
        {"key": "fl_tyre",       "label": "Front left tyre"},
        {"key": "fr_tyre",       "label": "Front right tyre"},
        {"key": "rl_tyre",       "label": "Rear left tyre"},
        {"key": "rr_tyre",       "label": "Rear right tyre"},
        {"key": "spare_tyre",    "label": "Spare tyre"},
        {"key": "alloy_fl",      "label": "Alloy/rim FL"},
        {"key": "alloy_fr",      "label": "Alloy/rim FR"},
        {"key": "alloy_rl",      "label": "Alloy/rim RL"},
        {"key": "alloy_rr",      "label": "Alloy/rim RR"},
        {"key": "brake_pads",    "label": "Brake pads"},
        {"key": "brake_disc",    "label": "Brake discs"},
        {"key": "suspension",    "label": "Suspension"},
    ],
    "testdrive": [
        {"key": "td_acceleration","label": "Acceleration"},
        {"key": "td_braking",    "label": "Braking"},
        {"key": "td_steering",   "label": "Steering response"},
        {"key": "td_gearshift",  "label": "Gear shifts (manual/auto)"},
        {"key": "td_clutch",     "label": "Clutch (if manual)"},
        {"key": "td_vibration",  "label": "Vibration"},
        {"key": "td_noise",      "label": "Noise during drive"},
        {"key": "td_abs",        "label": "ABS functioning"},
        {"key": "td_traction",   "label": "Traction control"},
        {"key": "td_ac_drive",   "label": "AC during drive"},
        {"key": "td_electronics","label": "Electronics/warnings"},
    ],
    "battery": [
        {"key": "bat_brand",     "label": "Battery brand"},
        {"key": "bat_health",    "label": "Battery health (%)"},
        {"key": "bat_capacity",  "label": "Battery capacity (kWh)"},
        {"key": "bat_cycles",    "label": "Charge cycles"},
        {"key": "bat_range",     "label": "Estimated range"},
        {"key": "charger_port",  "label": "Charging port condition"},
        {"key": "fast_charge",   "label": "Fast charge supported"},
        {"key": "bat_temp",      "label": "Battery temp normal"},
        {"key": "regenerative",  "label": "Regenerative braking"},
    ],
}
