# Generated by Django 5.2.12 on 2026-06-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task assigned"),
                            ("task_due", "Task due"),
                            ("auction_start", "Auction started"),
                            ("bid_update", "Bid update"),
                            ("deal_confirmed", "Deal confirmed"),
                            ("doc_pending", "Document pending"),
                            ("insp_assigned", "Inspection assigned"),
                            ("insp_decision", "Inspection approved/rejected"),
                            ("kyc_result", "KYC result"),
                            ("payment_ok", "Payment confirmed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("channels", models.JSONField(default=list)),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("is_read", models.BooleanField(default=False)),
                ("delivered", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
